# Generated by Django 3.2.7 on 2021-10-09 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominium.condominium')),
            ],
            options={
                'verbose_name': 'SubArea',
                'verbose_name_plural': 'SubAreas',
            },
        ),
    ]
