# Generated by Django 3.2.7 on 2021-10-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0005_auto_20211010_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Communique',
                'verbose_name_plural': 'Communiques',
            },
        ),
    ]
