# Generated by Django 3.2.7 on 2021-10-10 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0007_communique_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('schedule', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominium.condominium')),
            ],
            options={
                'verbose_name': 'CommonArea',
                'verbose_name_plural': 'CommonAreas',
            },
        ),
    ]
