# Generated by Django 3.2.7 on 2021-10-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0008_commonarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_card', models.FloatField()),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(max_length=255)),
                ('quantity_people', models.IntegerField(default=1)),
                ('comment', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
