# Generated by Django 3.2.7 on 2021-10-10 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0009_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='commonArea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condominium.commonarea'),
            preserve_default=False,
        ),
    ]
