# Generated by Django 3.2.7 on 2021-10-11 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('condominium', '0010_reservation_commonarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_date', models.DateField()),
                ('end_date', models.DateField()),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominium.condominium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AdminHistory',
                'verbose_name_plural': 'AdminHistories',
            },
        ),
    ]
