# Generated by Django 3.2.7 on 2021-10-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0012_alter_adminhistory_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhistory',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
