# Generated by Django 3.1.5 on 2021-09-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='s@s', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
