# Generated by Django 3.2.7 on 2021-10-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_identification_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lessee',
            field=models.BooleanField(default=False),
        ),
    ]
