# Generated by Django 3.2.7 on 2021-10-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification_card',
            field=models.FloatField(unique=True),
        ),
    ]
